import type { BusinessDefinition, BusinessType } from "./types";

export const BUSINESS_DEFINITIONS: Record<BusinessType, BusinessDefinition> = {
  mine: {
    type: "mine",
    name: "Mine",
    sector: "mining",
    managementLoad: 2,
    baseCapacity: 4,
    foundingCost: 80,
    maintenancePerTick: 0.35,
    employeeBase: 2,
    recipe: {
      inputs: { energy: 0.5 },
      outputs: { copper: 0.7, iron: 0.5 },
      capacityCost: 1,
    },
    primaryResources: ["copper", "iron"],
  },
  farm: {
    type: "farm",
    name: "Farm",
    sector: "agriculture",
    managementLoad: 1.5,
    baseCapacity: 5,
    foundingCost: 50,
    maintenancePerTick: 0.2,
    employeeBase: 2,
    recipe: {
      inputs: { energy: 0.2 },
      outputs: { food: 2.5 },
      capacityCost: 1,
    },
    primaryResources: ["food"],
  },
  power_plant: {
    type: "power_plant",
    name: "Power Plant",
    sector: "energy",
    managementLoad: 2.5,
    baseCapacity: 8,
    foundingCost: 120,
    maintenancePerTick: 0.5,
    employeeBase: 3,
    recipe: {
      inputs: {},
      outputs: { energy: 3 },
      capacityCost: 1,
    },
    primaryResources: ["energy"],
  },
  smelter: {
    type: "smelter",
    name: "Smelter",
    sector: "processing",
    managementLoad: 3,
    baseCapacity: 4,
    foundingCost: 110,
    maintenancePerTick: 0.45,
    employeeBase: 3,
    recipe: {
      inputs: { iron: 1.2, copper: 0.9, energy: 1.1 },
      outputs: { components: 0.7 },
      capacityCost: 1,
    },
    primaryResources: ["components", "iron", "copper"],
  },
  factory: {
    type: "factory",
    name: "Factory",
    sector: "manufacturing",
    managementLoad: 3,
    baseCapacity: 3,
    foundingCost: 150,
    maintenancePerTick: 0.6,
    employeeBase: 4,
    recipe: {
      inputs: { components: 1.0, energy: 1.2 },
      outputs: { machines: 0.4 },
      capacityCost: 1,
    },
    primaryResources: ["machines", "components"],
  },
  warehouse: {
    type: "warehouse",
    name: "Warehouse",
    sector: "warehousing",
    managementLoad: 2,
    baseCapacity: 1,
    foundingCost: 70,
    maintenancePerTick: 0.25,
    employeeBase: 1,
    recipe: null,
    primaryResources: ["iron", "copper", "food", "components", "machines"],
    storageCapacity: 500,
  },
  retailer: {
    type: "retailer",
    name: "Retailer",
    sector: "retail",
    managementLoad: 2,
    baseCapacity: 3,
    foundingCost: 60,
    maintenancePerTick: 0.3,
    employeeBase: 2,
    recipe: {
      inputs: { food: 1.5, machines: 0.05, components: 0.1 },
      outputs: {},
      capacityCost: 1,
    },
    primaryResources: ["food", "machines"],
  },
  bank: {
    type: "bank",
    name: "Bank",
    sector: "banking",
    managementLoad: 3,
    baseCapacity: 1,
    foundingCost: 200,
    maintenancePerTick: 0.4,
    employeeBase: 3,
    recipe: null,
    primaryResources: ["cash"],
  },
  logistics: {
    type: "logistics",
    name: "Logistics",
    sector: "transport",
    managementLoad: 2,
    baseCapacity: 4,
    foundingCost: 90,
    maintenancePerTick: 0.4,
    employeeBase: 3,
    recipe: {
      inputs: { energy: 0.8 },
      outputs: {},
      capacityCost: 1,
    },
    primaryResources: ["energy"],
  },
};

export const FOUNDABLE_TYPES: BusinessType[] = [
  "mine",
  "farm",
  "power_plant",
  "smelter",
  "factory",
  "warehouse",
  "retailer",
];
